/**
 * AUTO-GENERATED by scripts/offline-20m-audit.mjs.
 * Stage-1 offline audit writes this file. Do not hand-edit.
 *
 * An incomplete manifest must never 404 the factory as a band: the live
 * edgeQualityGate still decides per URL until a complete scan for this
 * CONTENT_VERSION lands.
 */
export const MANIFEST_COMPLETE = false;
export const MANIFEST_CONTENT_VERSION = '';
export const MANIFEST_CORPUS_SIZE = 20_000_000;
export const MANIFEST_SCANNED = 0;
export const MANIFEST_IDENTITY_COMPLETE = false;
export const MANIFEST_DOCUMENT_COMPLETE = false;
export const MANIFEST_JACCARD_COMPLETE = false;
export const QUARANTINE_IDS: readonly number[] = [];
