/**
 * AUTO-GENERATED by scripts/offline-20m-audit.mjs.
 * Stage-1 offline audit writes this file. Do not hand-edit.
 */
export const MANIFEST_COMPLETE = false;
export const MANIFEST_CONTENT_VERSION = '';
export const MANIFEST_CORPUS_SIZE = 20000000;
export const MANIFEST_SCANNED = 20000000;
export const MANIFEST_IDENTITY_COMPLETE = true;
export const MANIFEST_DOCUMENT_COMPLETE = false;
export const MANIFEST_JACCARD_COMPLETE = false;
export const QUARANTINE_IDS: readonly number[] = [];
